# Generated by Django 3.1.6 on 2022-04-23 01:27

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='courses',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='faculty', chained_model_field='faculty', on_delete=django.db.models.deletion.CASCADE, to='fees.course'),
        ),
    ]
