# Generated by Django 3.1.6 on 2022-05-28 08:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_auto_20220521_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_faculty', to='fees.faculty'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('bank teller', 'BANK TELLER'), ('online payment', 'ONLINE PAYMENT'), ('cash', 'CASH'), ('transfer', 'TRANSFER'), ('pos', 'POS')], max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_payment', to='fees.staff'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud_payment', to='fees.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud_faculty', to='fees.faculty'),
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark', to='fees.student')),
            ],
        ),
    ]
