# Generated by Django 3.1.6 on 2022-05-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_auto_20220528_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='slug',
            field=models.SlugField(default='remark'),
        ),
    ]
