# Generated by Django 3.1.6 on 2023-12-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0018_payment_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='remark',
            field=models.CharField(choices=[('complaint', 'COMPLAINT'), ('feedback', 'FEED BACK')], default='feedback', max_length=50),
        ),
    ]
