# Generated by Django 4.2 on 2024-08-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0020_alter_faculty_options_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'facultie'},
        ),
    ]
