# Generated by Django 4.2 on 2024-08-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0021_alter_faculty_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_payed',
        ),
        migrations.AddField(
            model_name='payment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proof/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
