# Generated by Django 4.2 on 2024-08-12 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0022_remove_student_is_payed_payment_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Resolved'), ('C', 'Closed')], default='P', max_length=1)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default='remark', max_length=100, unique=True)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.CASCADE, related_name='remark', to='fees.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
