# Generated by Django 4.2 on 2024-08-12 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0023_complaint_delete_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reference_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='slug',
            field=models.SlugField(default='complaint', max_length=100, unique=True),
        ),
    ]
