# Generated by Django 4.2 on 2024-08-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0025_alter_complaint_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reference_id',
            field=models.CharField(default='<function ', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
