# Generated by Django 4.2 on 2024-08-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0026_alter_complaint_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reference_id',
            field=models.CharField(default='82f78200-d', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='fees.student'),
        ),
    ]
