# Generated by Django 4.2 on 2024-08-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0027_alter_complaint_reference_id_alter_complaint_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reference_id',
            field=models.CharField(default='ff69824d-44c3-4c', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
