# Generated by Django 4.2 on 2024-08-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0028_alter_complaint_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reference_id',
            field=models.CharField(default='62c79d06-dc36-47', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
