# Generated by Django 4.2 on 2024-09-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0029_payment_complaint_alter_complaint_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reference_id',
            field=models.CharField(default='b27af596-5e20-40', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_payment', to='fees.staff'),
        ),
    ]
