# Generated by Django 4.2 on 2024-09-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0030_alter_complaint_reference_id_alter_payment_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('rejected', 'REJECTED')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reference_id',
            field=models.CharField(default='ab57878f-844a-41', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
