# Generated by Django 4.2 on 2024-09-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0031_remove_payment_is_confirmed_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='complaint',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reference_id',
            field=models.CharField(default='a5a15527-d2c0-45', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
