# Generated by Django 4.2 on 2025-08-11 16:17

from django.db import migrations, models
import fees.models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0033_alter_complaint_reference_id_alter_complaint_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reference_id',
            field=models.CharField(default='16d261eb-34de-43', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='academic_year',
            field=models.PositiveIntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=fees.models.current_year),
        ),
    ]
